make for git plugin

diff --git a/git-xcp-beta b/git-xcp-beta
--- a/git-xcp-beta
+++ b/git-xcp-beta
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-function check_complict {
+function check_conflict {
 	if $(git status --porcelain | grep UU); then
 	    echo Repo was Confilcted.; exit 1
 	fi
@@ -10,17 +10,16 @@ function check_clean {
 		echo Repo was NOT Cleaned.; exit 1
 	fi
 }
-STASH_ID="stash_id_tmp"
+tmp_stash_id="stash_id_tmp"
 function get_tmp_stash_id {
-	echo "$(git stash list | grep $STASH_ID | awk -F':' '{print $1}' | head -1)"
+	echo "$(git stash list | grep $tmp_stash_id | awk -F':' '{print $1}' | head -1)"
 }
-CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-
-check_complict
-git stash save -u $STASH_ID
+current_branch="$(git rev-parse --abbrev-ref HEAD)"
+check_conflict
+git stash save -u $tmp_stash_id
 check_clean
-git pull origin $CURRENT_BRANCH
-check_complict
+git pull origin $current_branch
+check_conflict
 echo "============ CLEANED. NOW START TASK... ============"
 
 
@@ -30,45 +29,42 @@ read  -rd '' BUILD_NUM <<< "$BUILD_NUM"
 
 re='^[0-9]+$'
 if ! [[ $BUILD_NUM =~ $re ]] ; then
-   echo "error: Can't Extract build number." >&2; exit 1
+   echo "error: Can't Extract build number. Maybe your project has not 'CURRENT_PROJECT_VERSION' key in plist." >&2; exit 1
 fi
 
 if [ "$1" == "--revert" ]; then
-    echo "============ NOW REVERT : Build $BUILD_NUM ============"
-
+    echo "# Now revert : Build $BUILD_NUM ..."
     TAG=beta/b$BUILD_NUM
-    LASTCOMMIT_SHA=$(git show-ref --heads --hash --tags "$TAG")
-    if [ -z "$LASTCOMMIT_SHA" ]; then
+    last_commit_sha=$(git show-ref --heads --hash --tags "$TAG")
+    if [ -z "$last_commit_sha" ]; then
     	echo "[!] Not found matched SHA via current build number"; exit 1
     fi
-    git revert $LASTCOMMIT_SHA --no-edit
-    git push origin $CURRENT_BRANCH
-
+    git revert $last_commit_sha --no-edit
+    git push origin $current_branch
     git fetch --tags
     git tag -d $TAG
     git push origin :refs/tags/$TAG
-    
+
 else
     if ! [ "$1" == "--exclude-new-buildnum" ]; then
         BUILD_NUM=$(agvtool next-version -all | tail -3 | awk 'NF{print $NF; exit}')
     fi
-
-    echo "============ NOW DEPLOY TO ORIGIN : Build $BUILD_NUM ============"
-
+    
+    echo "# Now deploy to origin : Build $BUILD_NUM"
     # push to origin
     git add -u
     git commit -m "[Build $BUILD_NUM - Beta]"
     $(git tag beta/b"$BUILD_NUM")
-    git push -f origin "$CURRENT_BRANCH":release-beta
-    git push origin $CURRENT_BRANCH
+    git push -f origin "$current_branch":release-beta
+    git push origin $current_branch
     $(git push origin beta/b"$BUILD_NUM")
 fi
 
 
 # undo stash
-STASHED_ID=$(get_tmp_stash_id)
-if [ -n "$STASHED_ID" ]; then
-	if [ -n "$(git stash pop "$STASHED_ID" --index | egrep "Dropped $STASHED_ID")" ]; then
+tmp_stash_id=$(get_tmp_stash_id)
+if [ -n "$tmp_stash_id" ]; then
+	if [ -n "$(git stash pop "$tmp_stash_id" --index | egrep "Dropped $tmp_stash_id")" ]; then
 		echo "Restored working directory and index state succesfully."
 	fi
 fi
