xcps - multi project target support

diff --git a/src/xcps-src b/src/xcps-src
--- a/src/xcps-src
+++ b/src/xcps-src
@@ -1,15 +1,22 @@
 source $(dirname $0)/xcp-begin
 
-plist_path=$(/usr/bin/xcrun xcodebuild -showBuildSettings -target $1 2>/dev/null | grep "INFOPLIST_FILE" | sed 's/[ ]*INFOPLIST_FILE = //')
+TARGET=$1
+plist_path=$(/usr/bin/xcrun xcodebuild -showBuildSettings -target $TARGET 2>/dev/null | grep "INFOPLIST_FILE" | sed 's/[ ]*INFOPLIST_FILE = //')
 if [ -z "$plist_path" ]; then
-	echo "[!] Not found plist of given target. $1"; exit 1
+	echo "[!] Not found plist of given target. $TARGET"; exit 1
 fi
 
 VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$plist_path")  
 BUILD_NUM=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$plist_path")  
-TARGET_TAG=submit/s"$BUILD_NUM"_"$VERSION"
+TARGET_TAG=submit/"$TARGET"/"$VERSION"_b"$BUILD_NUM"
+TARGET_BRANCH=release-submit-"$TARGET"
+DEST_BRANCH_PATH="$CURRENT_BRANCH":release-submit-"$TARGET"
 
-git push -f origin "$CURRENT_BRANCH":release-submit && git push origin $CURRENT_BRANCH
+if [ -n "git branch --list --all | grep remotes/origin | grep $TARGET_BRANCH" ]; then
+	git branch $TARGET_BRANCH
+fi
+
+git push -f origin $DEST_BRANCH_PATH && git push origin $CURRENT_BRANCH
 git tag "$TARGET_TAG" && git push origin "$TARGET_TAG"
 
 source $(dirname $0)/xcp-end
